#!/bin/bash
ID=$(id -u)
echo $0
echo $ID
TIMESTAMP=$(date +F-%H-%M-%S)
LOG_FILE=/tmp/$0.$TIMESTAMP.log

VAILDATE()
{
    if [ $1 -ne 0 ]
    then 
    echo "$2...failed"
    else 
    echo "$2...success"
    fi
}
if [ $ID -ne 0 ]
then 
echo "please run script with root user"
else
echo "you are root user"
fi

cd $1; find . -name "*.log" -type f -mmin +1 -delete &>>$LOG_FILE
#cd /tmp/shell; find . -name "*.log" -type f -mmin +1 -delete
VAILDATE $? "deletion is " &>>$LOG_FILE


