#!/bin/bash
ID=$(id -u)
echo "output is $ID"

if [ $ID -ne 0 ]
then
echo "error: script will run with root previlages"
exit 1
else 
echo "you are the root user"
fi   #it exits
yum install mysdasql -y

RULE=$(echo $?)
echo "output is $RULE"
if [ $RULE -ne 0 ]
then
echo "error: installation is failed"
exit 1
else 
echo "installation is successful"
fi

