#!/bin/bash
ID=$(id -u)
echo $0
echo $ID
TIMESTAMP=$(date +F-%H-%M-%S)
LOG_FILE=/tmp/$0.$TIMESTAMP.log

VAILDATE()
{
    if [ $1 -ne 0 ]
    then 
    echo "$2...failed"
    else 
    echo "$2...success"
    fi
}
if [ $ID -ne 0 ]
then 
echo "please run script with root user"
else
echo "you are root user"
fi

for package in $@
do 
yum list installed $package &>>LOG_FILE
if [ $? -ne 0 ]
then 
yum install $package -y &>>LOG_FILE
VAILDATE $? "installaation of $package"
else 
echo "$package is alrady installaed...SKIPPED"
fi
done
