#!/bin/bash
ID=$(id -u)

if [ $ID -ne 0 ]
then
echo "run the script with root previlages"
exit 1
else
echo "you are in root"
fi
yum install telnet -y 

RULE=$(echo $?)
if [ $RULE -ne 0]
then
echo "installation is failed"
exit 1
else 
echo "installation is success"
fi
