#!/bin/bash
ID=$(id -u)

TIMESTAMP=$(date +F-%H-%M-%S)
LOG_FILE=/tmp/$0.$TIMESTAMP.log


VALIDATE(){
    if [ $1 -ne 0 ]
    then 
    echo "$2.... failed "
    else 
    echo "$2...successful"
    fi
}


if [ $ID -ne 0 ]
then
echo "please run the script with root previlages"
exit 1
else
echo "you are root user"
fi

yum install gcc -y &>>$LOG_FILE

VALIDATE $? "installation is "


